exec e = <"echo" withargs ["hello"]>;
exec e1 = <"echo" withargs ["kenny"]>;
exec e2 = <"echo" withargs ["world"]>;
exec e4 = e * e1 + e2;

string s = ./e4;
./<"echo" withargs ["______________"]>;
./<"echo" withargs [s]>;

exec e5 = (e + e1) * (e2 + e);
exec e6 = (e * e1) + (e2 * e);

string s2 = ./e5;
string s3 = ./e6;
./<"echo" withargs ["______________"]>;
./<"echo" withargs [s2]>;
./<"echo" withargs ["______________"]>;
./<"echo" withargs [s3]>;