/*
    Creates a function to test integer operations and comparison
*/


void intArith(int a, int b) {
    print(a + b);
    print(a - b);
    print(a * b);
    print(a / b);
    print(a == b);
    print(a == a);
    print(a != b);
    print(a != a);
    print(a > b);
    print(a >= b);
    print(a < b);
    print(a <= b);
}

intArith(4, 3);
print('\n');
intArith(3, 3);
print('\n');
intArith(-4,1);
print('\n');
intArith(-1,-1)


